# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.12.3
_src_path: gl:openscm/copier-core-python-repository
conda_release: false
email: zecchetto@iiasa.ac.at
include_cli: false
name: MZ
notebook_based_docs: true
package_manager: uv
pandas_doctests: false
plot_dependencies: true
project_description_short: test fork+core
project_name_human: test fork
project_name_pip: test-fork
project_name_python: test_fork
project_url: https://github.com/mzecc/test_core_github.git
track_lock_file: true
